/**
 ******************************************************************************
 * @file    mx.c
 * @author  STMicroelectronics - AIS - MCD Team
 * @version 3.0.1
 * @date    21/01/2022 10:35:14
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"

/**
 * (USER_BUTTON_1) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_UB1InitParams = {
    MX_GPIO_Init, /* WARNING!: we need to define one GPIO_Init function for each PIN... if possible. */
    EXTI15_10_IRQn,
    GPIO_PIN_13,
    GPIOC
};

/**
 * TIM7 initialization parameters.
 */
const MX_TIMParams_t MX_TIM7InitParams = {
    .p_mx_init_f = MX_TIM7_Init,
    .p_tim = &htim7,
    .irq_n = TIM7_IRQn
};
