/**
 ******************************************************************************
 * @file    mx.c
 * @author  STMicroelectronics - AIS - MCD Team
 * @version 1.0.0
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2021 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "spi.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"

/**
 * SPI1 initialization parameters.
 */
const MX_SPIParams_t MX_SPI1InitParams = {
    .p_mx_init_f = MX_SPI1_Init,
    .p_spi_handle  = &hspi1,
    .p_mx_dma_init_f = MX_DMA_InitCustom,
    .spi_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .spi_dma_tx_irq_n = DMA1_Channel2_IRQn
};


/**
 * TIM2 initialization parameters.
 */
const MX_TIMParams_t MX_TIM2InitParams = {
    .p_mx_init_f = MX_TIM2_Init,
    .p_tim = &htim2,
    .irq_n = TIM2_IRQn
};

/**
 * PB13 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PB13InitParams = {
    MX_GPIO_PB13_Init,
    BUTTON_USER_EXTI_IRQn,
    GPIO_PIN_13,
    GPIOB
};

/**
 * PD2 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PD2InitParams = {
    MX_GPIO_PD2_Init,
    HardFault_IRQn, /* Not used */
    GPIO_PIN_2,
    GPIOD
};

/**
 * PD8 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PD8InitParams = {
    MX_GPIO_PD8_Init,
    HardFault_IRQn, /* Not used */
    GPIO_PIN_8,
    GPIOD
};

/**
 * PH1 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PH1InitParams = {
    MX_GPIO_PH1_Init,
    HardFault_IRQn, /* Not used */
    GPIO_PIN_1,
    GPIOH
};
