################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/adc.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/dfsdm.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/dma.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/gpio.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/i2c.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/mx.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/spi.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/sysinit_mx.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/tim.c \
/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/usart.c 

OBJS += \
./Application/mx/Src/adc.o \
./Application/mx/Src/dfsdm.o \
./Application/mx/Src/dma.o \
./Application/mx/Src/gpio.o \
./Application/mx/Src/i2c.o \
./Application/mx/Src/mx.o \
./Application/mx/Src/spi.o \
./Application/mx/Src/sysinit_mx.o \
./Application/mx/Src/tim.o \
./Application/mx/Src/usart.o 

C_DEPS += \
./Application/mx/Src/adc.d \
./Application/mx/Src/dfsdm.d \
./Application/mx/Src/dma.d \
./Application/mx/Src/gpio.d \
./Application/mx/Src/i2c.d \
./Application/mx/Src/mx.d \
./Application/mx/Src/spi.d \
./Application/mx/Src/sysinit_mx.d \
./Application/mx/Src/tim.d \
./Application/mx/Src/usart.d 


# Each subdirectory must supply rules for building sources it contributes
Application/mx/Src/adc.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/adc.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/dfsdm.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/dfsdm.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/dma.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/dma.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/gpio.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/gpio.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/i2c.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/i2c.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/mx.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/mx.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/spi.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/spi.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/sysinit_mx.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/sysinit_mx.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/tim.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/tim.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/mx/Src/usart.o: /Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC\ -\ JupyterNotebook\ -\ Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/mx/Src/usart.c Application/mx/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSYS_TP_MCU_STM32L4 -DSTM32L4R9xx -DSTM32L4R9ZIJx -DSTEVAL_STWINKT1 -DDEBUG -DSYS_DEBUG -DUSE_HAL_DRIVER -DUSE_FULL_ASSERT -DSYS_TRACE=0 -DSYS_DBG_ENABLE_TA4=0 -DARM_MATH_CM4 -D__FPU_PRESENT -c -I../../Inc -I../../X-CUBE-AI/App -I../../SensorManager/Inc -I../../signal_processing_lib/lib_features_extraction/Inc -I../../signal_processing_lib/gravity_filter/Inc -I../../DPU/Inc -I../../mx/Inc -I../../../../../../Drivers/CMSIS/Core/Include -I../../../../../../Drivers/CMSIS/DSP/Include -I../../../../../../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../../../../../../Drivers/STM32L4xx_HAL_Driver/Inc -I../../../../../../Drivers/BSP/Components/iis3dwb -I../../../../../../Drivers/BSP/Components/ism330dhcx -I../../../../../../Drivers/BSP/Components/hts221 -I../../../../../../Drivers/BSP/Components/lps22hh -I../../../../../../Middlewares/ST/eLooM/Inc -I../../../../../../Middlewares/ST/NanoEdge_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_AI_Library/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Core/Inc -I../../../../../../Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc -I../../../../../../Middlewares/ST/STM32_GenericFFT_Library/Inc -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I/FP-AI-MONITOR1_prj/Application/feature_extraction_library/Inc -I"/Users/leonardoiacussi/Desktop/PhD/ST_Motor/MFCC - JupyterNotebook - Firmware/Firmware_mfcc/Projects/STM32L4R9ZI-STWIN/Applications/FP-AI-MONITOR1/signal_processing_lib/feature_extraction_library/Inc" -O0 -ffunction-sections -fdata-sections -Wall -include ../../Inc/sysconfig.h -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-mx-2f-Src

clean-Application-2f-mx-2f-Src:
	-$(RM) ./Application/mx/Src/adc.d ./Application/mx/Src/adc.o ./Application/mx/Src/adc.su ./Application/mx/Src/dfsdm.d ./Application/mx/Src/dfsdm.o ./Application/mx/Src/dfsdm.su ./Application/mx/Src/dma.d ./Application/mx/Src/dma.o ./Application/mx/Src/dma.su ./Application/mx/Src/gpio.d ./Application/mx/Src/gpio.o ./Application/mx/Src/gpio.su ./Application/mx/Src/i2c.d ./Application/mx/Src/i2c.o ./Application/mx/Src/i2c.su ./Application/mx/Src/mx.d ./Application/mx/Src/mx.o ./Application/mx/Src/mx.su ./Application/mx/Src/spi.d ./Application/mx/Src/spi.o ./Application/mx/Src/spi.su ./Application/mx/Src/sysinit_mx.d ./Application/mx/Src/sysinit_mx.o ./Application/mx/Src/sysinit_mx.su ./Application/mx/Src/tim.d ./Application/mx/Src/tim.o ./Application/mx/Src/tim.su ./Application/mx/Src/usart.d ./Application/mx/Src/usart.o ./Application/mx/Src/usart.su

.PHONY: clean-Application-2f-mx-2f-Src

