/**
 ******************************************************************************
 * @file    mx.c
 * @author  STMicroelectronics - AIS - MCD Team
 * @version 1.0.0
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2021 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "i2c.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"

/**
 * I2C2 initialization parameters.
 */
const MX_I2CParams_t MX_I2C2InitParams = {
    .p_mx_init_f = MX_I2C2_Init,
    .p_i2c_handle = &hi2c2,
    .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
    .i2c_er_irq_n = I2C2_ER_IRQn,
    .i2c_ev_irq_n = I2C2_EV_IRQn,
    .i2c_dma_rx_irq_n = GPDMA1_Channel4_IRQn,
    .i2c_dma_tx_irq_n = GPDMA1_Channel5_IRQn
};

/**
 * TIM5 initialization parameters.
 */
const MX_TIMParams_t MX_TIM6InitParams = {
    .p_mx_init_f = MX_TIM6_Init,
    .p_tim = &htim6,
    .irq_n = TIM6_IRQn
};

/**
 * PH7 (LED1) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PH7InitParams = {
    MX_GPIO_PH7_Init,
    UsageFault_IRQn, /* not used. */
	LED_GREEN_Pin,
	LED_GREEN_GPIO_Port
};

/**
 * PC13 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PC13InitParams = {
    MX_GPIO_PC13_Init,
	USER_Button_EXTI_IRQn,
    GPIO_PIN_13,
    GPIOC
};

/**
 * PG2 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PG2InitParams = {
    MX_GPIO_PG2_Init,
	Mems_INT_LPS22HH_EXTI_IRQn,
	Mems_INT_LPS22HH_Pin,
	Mems_INT_LPS22HH_GPIO_Port
};
